# -*- coding: utf-8 -*-
"""Amazon_ml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LQgfvdx4MX7PEk0FtsRHhe29HM4XXwSD
"""

#!wget https://s3-ap-southeast-1.amazonaws.com/he-public-data/dataset52a7b21.zip

#!unzip /content/dataset52a7b21.zip

import pandas as pd
import csv

train = pd.read_csv('train.csv', sep=',', escapechar="\\", quoting=csv.QUOTE_NONE)

test = pd.read_csv('test.csv', sep=',', escapechar="\\", quoting=csv.QUOTE_NONE)

train=train.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
test=test.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)

Y = train.iloc[0:10000,-1:]

X = train.iloc[0:10000,0:4]

#X_test = test.iloc[:,1:5]

#Y_test = test.iloc[:,0]

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.4)

#from sklearn.svm import SVC
#sc= SVC()

from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier()

import re as re
from sklearn.metrics import accuracy_score

#def remove_tags(string):
 #   result = re.sub('<.*?>','',string)
  #  return result
#X_train.iloc[:, 1]=X_train.iloc[:, 1].apply(lambda cw : remove_tags(cw))    
#X_train.iloc[:, 2]=X_train.iloc[:, 2].apply(lambda cw : remove_tags(cw))  
#X_train.iloc[:, 1] = X_train.iloc[:, 1].str.replace('\W', '')
#X_train.iloc[:, 2] = X_train.iloc[:, 2].str.replace('\W', '')

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for i in range(0, 3):
  X_train.iloc[:, i] = le.fit_transform(X_train.iloc[:, i])
  X_test.iloc[:, i] = le.fit_transform(X_test.iloc[:, i])

#Y_train['BROWSE_NODE_ID'] = le.fit_transform(Y_train['BROWSE_NODE_ID'])
#X_train['TITLE']=X_train['TITLE'].str.replace('\f+', '')

random_forest.fit(X_train, Y_train.values.ravel())

#X_test = le.fit_transform(X_test)

Y_pred = random_forest.predict(X_test)
Y_pred_prob = random_forest.predict_proba(X_test)

print(accuracy_score(Y_test, Y_pred))
